
# mejkfajl k testovani zakladnich funkci core

all: math
	./math

math: math.cpp test.cpp
	g++ -o math -D_LINUX -D_NOXLIB math.cpp test.cpp 

struct: structures.cpp test.cpp
	g++ -o math -D_LINUX -D_NOXLIB structures.cpp test.cpp

